"""Property-based tests for SBOM domain model construction.

# Feature: sbom-writers, Property 1: Model construction preserves valid inputs

**Validates: Requirements 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8**

Property 1: Model construction preserves valid inputs.
For any set of field values that conform to the stated constraints (non-empty
strings where required, SPDX ID pattern SPDXRef-[a-zA-Z0-9.-]+, hash lengths
matching algorithms, license ID pattern LicenseRef-[a-zA-Z0-9.-]+),
constructing an SBOM value object SHALL succeed and all fields SHALL be
accessible with the exact values provided.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from debcraft.domain.sbom.values import (
    ChecksumAlgorithm,
    ExternalReferenceCategory,
    OutputFormat,
    RelationshipType,
    SBOMChecksum,
    SBOMCreationInfo,
    SBOMDocument,
    SBOMExternalReference,
    SBOMExtractedLicense,
    SBOMPackage,
    SBOMRelationship,
    WriterResult,
)

from .strategies import (
    md5_hashes,
    non_empty_text,
    sbom_checksums,
    sbom_creation_infos,
    sbom_documents,
    sbom_external_references,
    sbom_extracted_licenses,
    sbom_packages,
    sbom_relationships,
    sha1_hashes,
    sha256_hashes,
)

# ---------------------------------------------------------------------------
# Property 1: Model construction preserves valid inputs
# ---------------------------------------------------------------------------


@pytest.mark.unit
@pytest.mark.spdx
class TestProperty1ModelConstructionPreservesValidInputs:
    """Property 1: Model construction preserves valid inputs.

    For any valid inputs conforming to the stated constraints, constructing
    an SBOM value object SHALL succeed and all fields SHALL be accessible
    with the exact values provided.
    """

    # --- SBOMChecksum (Requirement 1.6) ---

    @settings(max_examples=100)
    @given(value=sha256_hashes)
    def test_checksum_sha256_preserves_fields(self, value: str) -> None:
        """SBOMChecksum with SHA256 preserves algorithm and value."""
        checksum = SBOMChecksum(algorithm=ChecksumAlgorithm.SHA256, value=value)
        assert checksum.algorithm == ChecksumAlgorithm.SHA256
        assert checksum.value == value

    @settings(max_examples=100)
    @given(value=sha1_hashes)
    def test_checksum_sha1_preserves_fields(self, value: str) -> None:
        """SBOMChecksum with SHA1 preserves algorithm and value."""
        checksum = SBOMChecksum(algorithm=ChecksumAlgorithm.SHA1, value=value)
        assert checksum.algorithm == ChecksumAlgorithm.SHA1
        assert checksum.value == value

    @settings(max_examples=100)
    @given(value=md5_hashes)
    def test_checksum_md5_preserves_fields(self, value: str) -> None:
        """SBOMChecksum with MD5 preserves algorithm and value."""
        checksum = SBOMChecksum(algorithm=ChecksumAlgorithm.MD5, value=value)
        assert checksum.algorithm == ChecksumAlgorithm.MD5
        assert checksum.value == value

    @settings(max_examples=100)
    @given(checksum=sbom_checksums())
    def test_checksum_composite_preserves_fields(self, checksum: SBOMChecksum) -> None:
        """SBOMChecksum generated by composite strategy preserves all fields."""
        reconstructed = SBOMChecksum(algorithm=checksum.algorithm, value=checksum.value)
        assert reconstructed.algorithm == checksum.algorithm
        assert reconstructed.value == checksum.value

    # --- SBOMExternalReference (Requirement 1.7) ---

    @settings(max_examples=100)
    @given(ref=sbom_external_references())
    def test_external_reference_preserves_fields(self, ref: SBOMExternalReference) -> None:
        """SBOMExternalReference preserves category, url, and comment."""
        assert ref.category in ExternalReferenceCategory
        assert ref.url  # non-empty
        reconstructed = SBOMExternalReference(
            category=ref.category,
            url=ref.url,
            comment=ref.comment,
        )
        assert reconstructed.category == ref.category
        assert reconstructed.url == ref.url
        assert reconstructed.comment == ref.comment

    # --- SBOMExtractedLicense (Requirement 1.8) ---

    @settings(max_examples=100)
    @given(license=sbom_extracted_licenses())
    def test_extracted_license_preserves_fields(self, license: SBOMExtractedLicense) -> None:  # noqa: A002
        """SBOMExtractedLicense preserves all fields."""
        assert license.license_id.startswith("LicenseRef-")
        assert license.extracted_text  # non-empty
        reconstructed = SBOMExtractedLicense(
            license_id=license.license_id,
            extracted_text=license.extracted_text,
            name=license.name,
            cross_references=license.cross_references,
        )
        assert reconstructed.license_id == license.license_id
        assert reconstructed.extracted_text == license.extracted_text
        assert reconstructed.name == license.name
        assert reconstructed.cross_references == license.cross_references

    # --- SBOMCreationInfo (Requirement 1.5) ---

    @settings(max_examples=100)
    @given(info=sbom_creation_infos())
    def test_creation_info_preserves_fields(self, info: SBOMCreationInfo) -> None:
        """SBOMCreationInfo preserves tools, created, creators, license_list_version."""
        assert len(info.tools) >= 1
        assert all(t.startswith("Tool: ") for t in info.tools)
        assert len(info.creators) >= 1
        assert all(c for c in info.creators)  # all non-empty
        reconstructed = SBOMCreationInfo(
            tools=info.tools,
            created=info.created,
            creators=info.creators,
            license_list_version=info.license_list_version,
        )
        assert reconstructed.tools == info.tools
        assert reconstructed.created == info.created
        assert reconstructed.creators == info.creators
        assert reconstructed.license_list_version == info.license_list_version

    # --- SBOMPackage (Requirement 1.3) ---

    @settings(max_examples=100)
    @given(pkg=sbom_packages())
    def test_package_preserves_fields(self, pkg: SBOMPackage) -> None:
        """SBOMPackage preserves all fields exactly as provided."""
        assert pkg.spdx_id.startswith("SPDXRef-")
        assert pkg.name  # non-empty
        reconstructed = SBOMPackage(
            spdx_id=pkg.spdx_id,
            name=pkg.name,
            version=pkg.version,
            supplier=pkg.supplier,
            download_location=pkg.download_location,
            checksums=pkg.checksums,
            package_url=pkg.package_url,
            concluded_license=pkg.concluded_license,
            declared_license=pkg.declared_license,
            copyright_text=pkg.copyright_text,
            description=pkg.description,
            external_references=pkg.external_references,
        )
        assert reconstructed.spdx_id == pkg.spdx_id
        assert reconstructed.name == pkg.name
        assert reconstructed.version == pkg.version
        assert reconstructed.supplier == pkg.supplier
        assert reconstructed.download_location == pkg.download_location
        assert reconstructed.checksums == pkg.checksums
        assert reconstructed.package_url == pkg.package_url
        assert reconstructed.concluded_license == pkg.concluded_license
        assert reconstructed.declared_license == pkg.declared_license
        assert reconstructed.copyright_text == pkg.copyright_text
        assert reconstructed.description == pkg.description
        assert reconstructed.external_references == pkg.external_references

    # --- SBOMRelationship (Requirement 1.4) ---

    @settings(max_examples=100)
    @given(rel=sbom_relationships())
    def test_relationship_preserves_fields(self, rel: SBOMRelationship) -> None:
        """SBOMRelationship preserves source_id, target_id, and relationship_type."""
        assert rel.source_id.startswith("SPDXRef-")
        assert rel.target_id.startswith("SPDXRef-")
        assert rel.relationship_type in RelationshipType
        reconstructed = SBOMRelationship(
            source_id=rel.source_id,
            target_id=rel.target_id,
            relationship_type=rel.relationship_type,
        )
        assert reconstructed.source_id == rel.source_id
        assert reconstructed.target_id == rel.target_id
        assert reconstructed.relationship_type == rel.relationship_type

    # --- SBOMDocument (Requirement 1.2) ---

    @settings(max_examples=100)
    @given(doc=sbom_documents())
    def test_document_preserves_fields(self, doc: SBOMDocument) -> None:
        """SBOMDocument preserves all fields exactly as provided."""
        assert doc.namespace  # non-empty
        assert doc.name  # non-empty
        assert len(doc.name) <= 255
        assert doc.creation_info is not None
        assert doc.root_package is not None
        assert isinstance(doc.packages, list)
        assert isinstance(doc.relationships, list)
        assert isinstance(doc.extracted_licenses, list)
        reconstructed = SBOMDocument(
            namespace=doc.namespace,
            name=doc.name,
            creation_info=doc.creation_info,
            root_package=doc.root_package,
            packages=doc.packages,
            relationships=doc.relationships,
            extracted_licenses=doc.extracted_licenses,
            comment=doc.comment,
            provenance_tool=doc.provenance_tool,
            provenance_timestamp=doc.provenance_timestamp,
        )
        assert reconstructed.namespace == doc.namespace
        assert reconstructed.name == doc.name
        assert reconstructed.creation_info == doc.creation_info
        assert reconstructed.root_package == doc.root_package
        assert reconstructed.packages == doc.packages
        assert reconstructed.relationships == doc.relationships
        assert reconstructed.extracted_licenses == doc.extracted_licenses
        assert reconstructed.comment == doc.comment
        assert reconstructed.provenance_tool == doc.provenance_tool
        assert reconstructed.provenance_timestamp == doc.provenance_timestamp

    # --- WriterResult (Requirement 3.3 — included for completeness) ---

    @settings(max_examples=100)
    @given(
        sha256=sha256_hashes,
        file_size=st.integers(min_value=0, max_value=10**9),
        diagnostics=st.lists(non_empty_text, max_size=10),
    )
    def test_writer_result_preserves_fields(
        self,
        sha256: str,
        file_size: int,
        diagnostics: list[str],
    ) -> None:
        """WriterResult preserves all fields exactly as provided."""
        output_path = Path("/tmp/test.json")
        fmt = OutputFormat.SPDX_2_3
        result = WriterResult(
            output_path=output_path,
            format=fmt,
            sha256=sha256,
            file_size=file_size,
            diagnostics=diagnostics,
        )
        assert result.output_path == output_path
        assert result.format == fmt
        assert result.sha256 == sha256
        assert result.file_size == file_size
        assert result.diagnostics == diagnostics
